apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
      - name: stock-api
        image: stock-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000